<a href="https://colab.research.google.com/github/Bonacelli/Finance/blob/main/01_Revis%C3%A3o_Python_B%C3%A1sico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introdução



In [ ]:
print("Olá mundo!")

Olá mundo!


In [ ]:
for i in range(3):
  print(i)

0
1
2


Qual seria o valor futuro se eu investisse R$ 1000 por 1 ano, com retorno de 5% ao ano?

In [ ]:
VP = 1000
i = 0.05
n = 1
VF = VP * ((1+i)**n)
VF

1050.0

Qual seria o valor presente se eu tivesse que descontar 1050 a uma taxa anual de 5% por um período de um ano?

In [ ]:
VF = 1050
i = 0.05
n = 1
VP = VF / ((1+i)**n)
VP

1000.0

#Listas

In [ ]:
frutas = ['maça', 'banana', 'laranja', 'pera']

In [ ]:
frutas

['maça', 'banana', 'laranja', 'pera']

In [ ]:
numeros = [1,5,3,4,2]
numeros

[1, 5, 3, 4, 2]

In [ ]:
lista = ['a','b','c', frutas, numeros]
lista

['a', 'b', 'c', ['maça', 'banana', 'laranja', 'pera'], [1, 5, 3, 4, 2]]

In [ ]:
frutas[3]

'pera'

In [ ]:
frutas[-1]

'pera'

In [ ]:
lista[1:-1]

['b', 'c', ['maça', 'banana', 'laranja', 'pera']]

In [ ]:
lista[2:]

['c', ['maça', 'banana', 'laranja', 'pera'], [1, 5, 3, 4, 2]]

In [ ]:
lista[2:4]

['c', ['maça', 'banana', 'laranja', 'pera']]

In [ ]:
frutas.append('melao')
frutas

['maça', 'banana', 'laranja', 'pera', 'melao']

In [ ]:
frutas.pop()
frutas

['maça', 'banana', 'laranja', 'pera']

In [ ]:
frutas.pop(0)
frutas

['laranja', 'pera']

In [ ]:
frutas[1] = 'uva'

In [ ]:
frutas

['laranja', 'uva']

#Tuplas

In [ ]:
marcas = ('gm', 'ford', 'fiat','vw')
marcas

('gm', 'ford', 'fiat', 'vw')

In [ ]:
cores = 'amarelo', 'vermelho', 'branco'
cores

('amarelo', 'vermelho', 'branco')

Tuplas não suportam alterações como nas listas

Um caso comum de uso é em funções que retornam vários valores

In [ ]:
x = 1.5
x.as_integer_ratio()

(3, 2)

In [ ]:
numerador, denominador = x.as_integer_ratio()

In [ ]:
numerador

3

In [ ]:
denominador

2

#Dicionários

In [ ]:
notas = {'portugues':8, 'ingles':7.4, 'matemática':9}
notas

{'ingles': 7.4, 'matemática': 9, 'portugues': 8}

In [ ]:
notas['matemática']

9

In [ ]:
notas['geografia'] = 8.2
notas

{'geografia': 8.2, 'ingles': 7.4, 'matemática': 9, 'portugues': 8}

#Estruturas Condicionais

In [ ]:
x = 1
y = 5

In [ ]:
x == 1

True

In [ ]:
x == 2

False

In [ ]:
x > 0 and  y < 2

False

In [ ]:
x > 0 or y < 2

True

In [ ]:
idade = 17
if idade < 18:
  print("Menor de idade")
else:
  print("Maior de idade")

Menor de idade


In [ ]:
estado = "BA"
if estado == "BA":
  print("Oxente!")
elif estado == "MG":
  print("Uai!")
else:
  print("Sem sotaque")

Oxente!


#Estruturas de Repetição

In [ ]:
lista = [1,2,3,'cachorro','gato','papagaio']

In [ ]:
for cada_item in lista:
  print(cada_item)

1
2
3
cachorro
gato
papagaio


In [ ]:
for valor in range(5):
  print(valor)

0
1
2
3
4


In [ ]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |

In [ ]:
for i in range(1,6,1):
  print(i)

1
2
3
4
5


In [ ]:
for i  in range(2,11,2):
  print(i)

2
4
6
8
10


In [ ]:
x = 0
while x < 5:
  print(x)
  x += 1

0
1
2
3
4


In [ ]:
i = 0
while True:
  print(i)
  i += 1
  if i >= 5:
    print('Lotado')
    break

0
1
2
3
4
Lotado


# Funções

In [ ]:
def exibir_mensagem(mensagem):
  print("Mensagem:", mensagem)

In [ ]:
exibir_mensagem("Olá!")

Mensagem: Olá!


In [ ]:
def exibir_dados(nome, idade):
  print("Meu nome é {}".format(nome))
  print("Tenho {} anos.".format(idade))

In [ ]:
exibir_dados("Henrique", 25)

Meu nome é Henrique
Tenho 25 anos.


In [ ]:
def ao_quadrado(numero):
  quad = numero ** 2
  return quad

In [ ]:
ao_quadrado(5)

25

In [ ]:
def argumentos(a, b=0, c=10):
  print("a =", a)
  print("b =", b)
  print("c =", c)
  return a + b + c

In [ ]:
argumentos(1)

a = 1
b = 0
c = 10


11

In [ ]:
argumentos(2,3,5)

a = 2
b = 3
c = 5


10

#Módulos e Pacotes

In [ ]:
import numpy

In [ ]:
numpy.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
import numpy as np

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
from numpy import ones

In [ ]:
ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
!pip install yfinance

     |████████████████████████████████| 5.5MB 5.6MB/s 
  Created wheel for yfinance: filename=yfinance-0.1.59-py2.py3-none-any.whl size=23442 sha256=f0ae5424599188518cad6c2837033c89071329939880812dcb4a2bdcab360b57
  Stored in directory: /root/.cache/pip/wheels/f8/2a/0f/4b5a86e1d52e451757eb6bc17fd899629f0925c777741b6d04
Successfully built yfinance
  Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6


In [ ]:
import yfinance as yf

In [ ]:
yf.download('^BVSP')

[*********************100%***********************]  1 of 1 completed


Open           High  ...      Adj Close   Volume
Date                                      ...                        
1993-04-27      24.799999      25.400000  ...      24.500000        0
1993-04-28      24.500000      24.600000  ...      24.299999        0
1993-04-29      24.299999      24.799999  ...      23.700001        0
1993-04-30      23.700001      24.200001  ...      24.100000        0
1993-05-03      24.100000      24.400000  ...      24.100000        0
...                   ...            ...  ...            ...      ...
2021-04-05  115262.000000  117668.000000  ...  117518.000000  7245100
2021-04-06  117519.000000  118213.000000  ...  117499.000000  6800800
2021-04-07  117499.000000  118303.000000  ...  117624.000000        0
2021-04-08  117624.000000  118850.000000  ...  118313.000000  8778200
2021-04-09  118313.000000  118643.000000  ...  117670.000000  7739400

[6912 rows x 6 columns]