<a href="https://colab.research.google.com/github/Bonacelli/Finance/blob/main/01_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 

NumPy é uma Biblioteca de Álgebra Linear para Python muito rápida pois tem seu *core* implementado em C.

É a base de muitas outras bibliotecas, como o Pandas que vamos ver a seguir.

Documentação oficial: https://numpy.org/doc/stable/

In [1]:
import numpy as np

## **1. Criando Numpy Arrays**

### **1.1 A partir de listas**

In [2]:
lista = [1,2,3]

In [3]:
lista

[1, 2, 3]

In [4]:
np_array = np.array(lista)

In [5]:
np_array

array([1, 2, 3])

In [6]:
type(np_array)

numpy.ndarray

### **1.2 Através de métodos internos**

#### **arange**

Para um dado intervalo retorna valores igualmente espaçados a partir de um incremento fixo

`np.arange([start], [stop], [step], [dtype=None])`



In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

#### **linspace**
Para um dado intervalo retorna valores igualmente espaçados a partir do número total de elementos fornecidos

`linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)`

In [9]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [10]:
np.linspace(0,10,20, endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

#### **zeros e uns**

Gerando arrays de zeros ou uns

`zeros(shape, dtype=float, order='C')`

`ones(shape, dtype=None, order='C')`

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### **Matriz Identidade**

Cria uma matriz Identidade

`eye(N, M=None, k=0, dtype=float, order='C'`

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### **1.3 Através do Gerador de Números Aleatórios (Random)**

O Numpy também tem várias maneiras de criar matrizes de números aleatórios:

#### rand
Crie uma matriz de um dado formato e preenche com
amostras aleatórias de uma distribuição uniforme
sobre `` [0, 1) ``.

`rand(d0, d1, ..., dn)`

In [16]:
np.random.rand(2)

array([0.08047097, 0.03593906])

In [17]:
np.random.rand(3,3,3)

array([[[0.4166612 , 0.49537274, 0.2006481 ],
        [0.65879722, 0.5963937 , 0.52349213],
        [0.11465451, 0.91158662, 0.54632547]],

       [[0.42455984, 0.29837757, 0.48160962],
        [0.61518941, 0.78380469, 0.92859065],
        [0.8364836 , 0.02197083, 0.26726078]],

       [[0.527708  , 0.9637461 , 0.34711274],
        [0.03968638, 0.27940913, 0.78598741],
        [0.238915  , 0.14293812, 0.60670832]]])

#### randn

Retorne uma amostra (ou amostras) da distribuição "normal padrão". Ao contrário do rand, que é uniforme:

`randn(d0, d1, ..., dn)`

In [18]:
np.random.randn(1)

array([-0.25561718])

In [19]:
np.random.randn(3,3)

array([[ 1.50395019,  0.20329579,  0.95393145],
       [ 0.20744576, -0.16028879,  0.89745974],
       [-0.1130521 ,  0.20435255, -0.83666128]])

#### randint

Retorna inteiros aleatórios

`randint(low, high=None, size=None, dtype=int)`

In [20]:
np.random.randint(1,10)

4

In [21]:
np.random.randint(1,10,3)

array([3, 4, 8])

In [22]:
np.random.randint(1,10,(5,5))

array([[8, 2, 4, 2, 3],
       [1, 8, 3, 8, 9],
       [3, 7, 8, 6, 9],
       [9, 8, 9, 4, 1],
       [7, 5, 3, 4, 2]])

## **2. Atributos e métodos dos Numpy Arrays**

### Encontrando valores máximos e mínimos

`max(), min(), argmax(), argmin()`

In [23]:
vetor = np.random.randint(1,20, 5)

In [24]:
vetor

array([15,  2, 16,  7, 18])

In [25]:
vetor.max()

18

In [26]:
vetor.argmax()

4

In [27]:
vetor.min()

2

In [28]:
vetor.argmin()

1

### Alterando o formato da Matriz

In [29]:
matriz = np.arange(25)

In [30]:
matriz

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
matriz.shape

(25,)

In [32]:
matriz.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
matriz = matriz.reshape(5,5)

In [34]:
matriz.shape

(5, 5)