<a href="https://colab.research.google.com/github/Bonacelli/Finance/blob/main/03_Numpy_%C3%8Dndice_e_Sele%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy - Indexação e Seleção

In [1]:
import numpy as np

In [14]:
vetor = np.arange(1,25,3)

In [3]:
vetor

array([ 1,  4,  7, 10, 13, 16, 19, 22])

## Indexação e seleção por colchetes

Muito semelhante às listas Python:

`vetor[inicio : fim : passo]`

In [4]:
vetor[2]

7

In [5]:
vetor[0:3]

array([1, 4, 7])

In [6]:
vetor[:6:2]

array([ 1,  7, 13])

In [7]:
vetor[::-1]

array([22, 19, 16, 13, 10,  7,  4,  1])

### Atribuição de Valores

In [8]:
vetor

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [9]:
vetor[:3] = 100
vetor

array([100, 100, 100,  10,  13,  16,  19,  22])

In [10]:
vetor_novo = vetor[:3]
vetor_novo

array([100, 100, 100])

In [11]:
vetor_novo[:] = 99
vetor_novo

array([99, 99, 99])

In [12]:
vetor

array([99, 99, 99, 10, 13, 16, 19, 22])

In [15]:
vetor_novo = vetor.copy()
vetor_novo

array([ 1,  4,  7, 10, 13, 16, 19, 22])

## Selecionando Elementos em Matrizes

In [16]:
matriz = np.array(([5,10,15], [20,25,30],[35,40,45]))

In [17]:
matriz

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
matriz[0]

array([ 5, 10, 15])

In [20]:
matriz[1][1]

25

In [21]:
matriz[1,1]

25

In [22]:
matriz[:,0]

array([ 5, 20, 35])

In [23]:
matriz[1:,1:]

array([[25, 30],
       [40, 45]])

## Seleção Condicional

In [25]:
vetor

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [26]:
vetor > 5

array([False, False,  True,  True,  True,  True,  True,  True])

In [27]:
filtro = vetor > 5

In [28]:
vetor[filtro]

array([ 7, 10, 13, 16, 19, 22])

In [29]:
vetor[vetor > 10]

array([13, 16, 19, 22])

In [30]:
vetor[vetor < 5]

array([1, 4])